---
exclude: alembic|nginx
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: end-of-file-fixer
  - repo: https://github.com/pycqa/isort # sorts imports
    rev: 5.13.2
    hooks:
      - id: isort
        args: [--line-length=120]
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        args: [--config, pyproject.toml]
        additional_dependencies:
          - "click==8.1.3"
